-- =====================================================
-- PROJECT: Superstore Sales Analysis
-- TOOL: MySQL
-- DATABASE: sales_project
-- PURPOSE: Analyze sales, profit, and business performance
-- =====================================================


-- =====================================================
-- DATA UNDERSTANDING
-- =====================================================

-- View all records from the dataset
-- Purpose: Understand the raw data and available columns

SELECT *
FROM sales_project.`sample_ superstore`;


-- Check the structure of the dataset
-- Purpose: View column names, data types, and table details

DESCRIBE sales_project.`sample_ superstore`;


-- Count the total number of records
-- Purpose: Understand the size of the dataset

SELECT COUNT(*) AS Total_Records
FROM sales_project.`sample_ superstore`;



-- =====================================================
-- DATA CLEANING
-- =====================================================

-- Check for missing values in important columns
-- Purpose: Ensure there are no NULL values before analysis

SELECT
    SUM(CASE WHEN Sales IS NULL THEN 1 ELSE 0 END) AS Missing_Sales,
    SUM(CASE WHEN Profit IS NULL THEN 1 ELSE 0 END) AS Missing_Profit,
    SUM(CASE WHEN Quantity IS NULL THEN 1 ELSE 0 END) AS Missing_Quantity,
    SUM(CASE WHEN Category IS NULL THEN 1 ELSE 0 END) AS Missing_Category,
    SUM(CASE WHEN `Customer ID` IS NULL THEN 1 ELSE 0 END) AS Missing_Customer_ID
FROM sales_project.`sample_ superstore`;


-- Check for duplicate Row IDs
-- Purpose: Ensure each record is unique

SELECT
    `Row ID`,
    COUNT(*) AS Duplicate_Count
FROM sales_project.`sample_ superstore`
GROUP BY `Row ID`
HAVING COUNT(*) > 1;


-- View unique product categories
-- Purpose: Verify there are no inconsistent category values

SELECT DISTINCT Category
FROM sales_project.`sample_ superstore`;


-- View unique customer segments
-- Purpose: Verify customer segment values

SELECT DISTINCT Segment
FROM sales_project.`sample_ superstore`;


-- View unique regions
-- Purpose: Verify region values

SELECT DISTINCT Region
FROM sales_project.`sample_ superstore`;



-- =====================================================
-- OVERALL BUSINESS KPIs
-- =====================================================

-- Calculate total sales generated
-- Purpose: Measure overall revenue generated by the business

SELECT ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`;


-- Calculate total profit earned
-- Purpose: Measure overall profitability of the business

SELECT ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`;


-- Calculate total quantity of products sold
-- Purpose: Understand total product volume sold

SELECT SUM(Quantity) AS Total_Quantity_Sold
FROM sales_project.`sample_ superstore`;


-- Calculate average sales per order
-- Purpose: Understand the average revenue generated per order

SELECT ROUND(AVG(Sales), 2) AS Average_Sales
FROM sales_project.`sample_ superstore`;


-- Calculate average profit per order
-- Purpose: Understand the average profit earned per order

SELECT ROUND(AVG(Profit), 2) AS Average_Profit
FROM sales_project.`sample_ superstore`;

-- =====================================================
-- CATEGORY ANALYSIS
-- =====================================================

-- Analyze sales performance by category
-- Purpose: Identify which category generates the highest revenue

SELECT
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY Category
ORDER BY Total_Sales DESC;


-- Analyze profit performance by category
-- Purpose: Identify which category contributes the highest profit

SELECT
    Category,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY Category
ORDER BY Total_Profit DESC;



-- =====================================================
-- PRODUCT ANALYSIS
-- =====================================================

-- Find the top 10 products based on sales
-- Purpose: Identify products generating the highest revenue

SELECT
    `Product Name`,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY `Product Name`
ORDER BY Total_Sales DESC
LIMIT 10;


-- Find the top 10 products based on profit
-- Purpose: Identify products generating the highest profit

SELECT
    `Product Name`,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY `Product Name`
ORDER BY Total_Profit DESC
LIMIT 10;


-- Find the bottom 10 products based on profit
-- Purpose: Identify products with the lowest profit or possible losses

SELECT
    `Product Name`,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY `Product Name`
ORDER BY Total_Profit ASC
LIMIT 10;


-- Analyze sales by sub-category
-- Purpose: Identify which sub-categories generate the highest sales

SELECT
    `Sub-Category`,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY `Sub-Category`
ORDER BY Total_Sales DESC;


-- Analyze profit by sub-category
-- Purpose: Identify which sub-categories contribute the highest profit

SELECT
    `Sub-Category`,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY `Sub-Category`
ORDER BY Total_Profit DESC;


-- Find sub-categories with the lowest profit
-- Purpose: Identify sub-categories that are causing losses or low profitability

SELECT
    `Sub-Category`,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY `Sub-Category`
ORDER BY Total_Profit ASC;

-- =====================================================
-- CUSTOMER ANALYSIS
-- =====================================================

-- Find the top 10 customers based on sales
-- Purpose: Identify customers generating the highest revenue

SELECT
    `Customer ID`,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY `Customer ID`
ORDER BY Total_Sales DESC
LIMIT 10;


-- Find the top 10 customers based on profit
-- Purpose: Identify customers generating the highest profit for the business

SELECT
    `Customer ID`,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY `Customer ID`
ORDER BY Total_Profit DESC
LIMIT 10;


-- Find customers with the lowest profit or losses
-- Purpose: Identify customers where the business earned low profit or faced losses

SELECT
    `Customer ID`,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY `Customer ID`
ORDER BY Total_Profit ASC
LIMIT 10;


-- Analyze customer performance by segment
-- Purpose: Understand which customer segment contributes the highest sales and profit

SELECT
    Segment,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY Segment
ORDER BY Total_Sales DESC;



-- =====================================================
-- REGIONAL ANALYSIS
-- =====================================================

-- Analyze sales performance by region
-- Purpose: Identify regions generating the highest revenue

SELECT
    Region,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY Region
ORDER BY Total_Sales DESC;


-- Analyze profit performance by region
-- Purpose: Identify regions contributing the highest profit

SELECT
    Region,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY Region
ORDER BY Total_Profit DESC;


-- Find states with highest sales
-- Purpose: Identify top-performing states based on revenue

SELECT
    State,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;


-- Find states with highest profit
-- Purpose: Identify top-performing states based on profitability

SELECT
    State,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY State
ORDER BY Total_Profit DESC
LIMIT 10;


-- Find states with lowest profit or losses
-- Purpose: Identify states where the business is performing poorly

SELECT
    State,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY State
ORDER BY Total_Profit ASC
LIMIT 10;

-- =====================================================
-- DISCOUNT ANALYSIS
-- =====================================================

-- Analyze average discount by category
-- Purpose: Identify which product category receives the highest average discount

SELECT
    Category,
    ROUND(AVG(Discount), 2) AS Average_Discount
FROM sales_project.`sample_ superstore`
GROUP BY Category
ORDER BY Average_Discount DESC;


-- Analyze average profit by discount
-- Purpose: Understand how different discount levels affect profit

SELECT
    Discount,
    ROUND(AVG(Profit), 2) AS Average_Profit
FROM sales_project.`sample_ superstore`
GROUP BY Discount
ORDER BY Discount;


-- Analyze total sales and profit by discount
-- Purpose: Compare business performance across different discount levels

SELECT
    Discount,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY Discount
ORDER BY Discount;



-- =====================================================
-- TIME ANALYSIS
-- =====================================================

-- Analyze yearly sales
-- Purpose: Identify sales performance across different years

SELECT
    YEAR(`Order Date`) AS Order_Year,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY YEAR(`Order Date`)
ORDER BY Order_Year;


-- Analyze yearly profit
-- Purpose: Identify profit performance across different years

SELECT
    YEAR(`Order Date`) AS Order_Year,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY YEAR(`Order Date`)
ORDER BY Order_Year;


-- Analyze monthly sales
-- Purpose: Identify monthly sales trends

SELECT
    MONTHNAME(`Order Date`) AS Month_Name,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY MONTH(`Order Date`), MONTHNAME(`Order Date`)
ORDER BY MONTH(`Order Date`);


-- Analyze monthly profit
-- Purpose: Identify monthly profit trends

SELECT
    MONTHNAME(`Order Date`) AS Month_Name,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY MONTH(`Order Date`), MONTHNAME(`Order Date`)
ORDER BY MONTH(`Order Date`);



-- =====================================================
-- SHIPPING ANALYSIS
-- =====================================================

-- Analyze sales by shipping mode
-- Purpose: Identify which shipping mode generates the highest sales

SELECT
    `Ship Mode`,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_project.`sample_ superstore`
GROUP BY `Ship Mode`
ORDER BY Total_Sales DESC;


-- Analyze profit by shipping mode
-- Purpose: Identify which shipping mode generates the highest profit

SELECT
    `Ship Mode`,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales_project.`sample_ superstore`
GROUP BY `Ship Mode`
ORDER BY Total_Profit DESC;



-- =====================================================
-- PROFIT MARGIN ANALYSIS
-- =====================================================

-- Calculate overall profit margin
-- Purpose: Measure business profitability as a percentage of total sales

SELECT
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percentage
FROM sales_project.`sample_ superstore`;